name = "eco-game"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-17"

[[d1_databases]]
binding = "DB"
database_name = "ecogame-db"
database_id = "f70551f2-c157-4e18-87b4-f2b41d67393d"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "df28f4248d584c94a92a9d70bc16b4e6"

# DO 관련 설정 삭제됨
[triggers]
crons = ["0 * * * *"]
